### ISSUE TITLE
Bug in Menus admin screen

### ISSUE THREAD

**Issue by superbp** [NateWr/food-and-drink-menu#17]
The plugin is actually working just fine on the latest version of Wordpress (4.3.1), but there is one glitch on the main Menus admin screen. Under the "Sections" column a few of my menu sections are listed properly, but several of them cause an error message to show. Each section with an error shows: `Notice: Undefined offset: 11 in /path/to/site/wp-content/plugins/food-and-drink-menu/cpts.php on line 673`

It doesn't seem to actually affect the plugin functions, but I thought I would point it out.

**Comment by NateWr** [comment]
Thanks for reporting. I'm on holiday at the moment but I'll take a look when I'm back.

**Comment by NateWr** [comment]
@superbp I've fixed the issue in the commit above. It will go out with the next update to the plugin.
