### ISSUE TITLE
Multiple menus with the same menu sections

### ISSUE THREAD

**Issue by JPG-Consulting** [NateWr/food-and-drink-menu#26]
Hi,

I have several menus which will use the same menu section name (For example "Starters", "Desserts",...). However this are seperate menus and should not share the same menu items. To solve this issue I should create something like "Desserts 2" which looks a bit ugly. Is there any way to make that work?

**Comment by NateWr** [comment]
Hi @JPG-Consulting,

This is unfortunately a limitation of the taxonomy system in WordPress. You can't have two terms in the same taxonomy with the same name.

My plan is to allow a menu section name to be overridden when desired, by storing a separate title as term meta. However, I can't promise this will be fixed very soon. I want to roll it out as part of a broader set of changes but have struggled to find the time to implement it.

It's definitely on my radar though.

In the meantime, probably the easiest workaround is to do some coding work within the templates themselves. For instance, the following would display a menu section title with all numbers and outer spaces removed in the `menu-section.php` template:

```
<?php 
$title = preg_replace('/[0-9]+/', '', $this->title);
echo trim($title);
?>
```

**Comment by NateWr** [comment]
A facility for using unique section titles for each menu was added in 4c4d2403592fd24e5d27196b0bddddfab8b3cabc, 371c74e84db8d8d978235ce0b54615387e599b0a and 22df68759a9e1d280abb09ffbe37243e26b14584. It will go out with the next version (1.5).
