### ISSUE TITLE
Unable to move available sections to sections

### ISSUE THREAD

**Issue by jacob-v-dam** [NateWr/food-and-drink-menu#31]
I installed the latest version from github. Now i'm unable to move sections to columns. They are stuck in available sections.

**Comment by NateWr** [comment]
Hi @jacob-v-dam,

I'm about to release some bigger changes to the plugin. As part of that, I now use a build process using grunt, a npm-based task runner, to compile the JavaScript files. Unless you've compiled the files none of the JavaScript will work for you.

If you're familiar with npm and grunt, you can run `grunt build` to build the JS files.

In the future, I'll try to ensure that tagged releases have packaged `.zip` files attached to them if you want to install via GitHub releases. But in general I only really support the stable version from the wordpress.org plugin directory. These changes should be landing there sometime this week.
