### ISSUE TITLE
Requesting Menu from outside

### ISSUE THREAD

**Issue by WizzardMaker** [NateWr/food-and-drink-menu#37]
Hello, I have a website with your plugin. Now I want to access my menus from my Android App, but the problem is, I don't know what item belongs to what menu. I saw that you work with WP_QUERY, but I only want to use SQL. Is there a list, or some other way to find out what item belongs to what Menu?

**Comment by NateWr** [comment]
Hi @WizzardMaker,

Menu items are assigned to Menu Sections. These Menu Sections are then assigned to Menus. Under-the-hood, Menu Items and Menus are "Posts", in WordPress vernacular, and the Menu Sections are a "Taxonomy". You'll find the post type slugs here:

https://github.com/NateWr/food-and-drink-menu/blob/master/food-and-drink-menu.php#L30-L31

And the taxonomy slug here:

https://github.com/NateWr/food-and-drink-menu/blob/master/includes/class-custom-post-types.php#L104

If you want to retrieve items from a menu, you'll have to write SQL to do the following:

1. Get the post meta data from the Menu. Read the `fdm_menu_column_one` and `fdm_menu_column_two` rows which contain the IDs of Menu Section taxonomy terms.

2. Retrieve all Menu Item posts and post metadata assigned to the Menu Section taxonomy term ids.
