### ISSUE TITLE
How do I align fdm-item-price and fdm-item-title?

### ISSUE THREAD

**Issue by Cphhygge** [NateWr/food-and-drink-menu#38]
Hey Nate,

First, thank you for your awesome plugin - it works very well for me, starting up a small café!

I have just this one question - as stated in the headline: How do I align fdm-item-price and fdm-item-title?

My quick/extra CSS looks like this:

```
@media (max-width: 768px) {

.fdm-columns-2 .fdm-column {
	width: 100%;
	float: none;
	margin: 0;
	}
}

.fdm-item-has-price .fdm-item-panel p {
	padding-right: 0%; 
}

.fdm-item-price-wrapper {
	position: absolute;
	width: 100%;
	text-align: right;
	top: 0;
	right: 0;
	white-space: nowrap;
	font-size: 16px;
	font-weight: bold;
	
}

.fdm-menu {
    color: #000000;
  }

.fdm-item-panel .fdm-item-title {
	font-size: 16px;
 } 
```
----
My problem is thus, that I want to align the two pieces of information. But it does not seem to work. After 6 hours of trying, I'm throwing in my towel...

I am not strong i coding, and have made my website using the 'Bistro' theme from 'athemes' (if that info is needed?).

Can you please help me on this one?

All the best,

Christian

**Comment by NateWr** [comment]
Hi Christian,

Can you send me a link to the menu on your site?

**Comment by Cphhygge** [comment]
Hi igain Nate, 

Yea, ofc, doh! :P http://cphhygge.dk/menu/

**Comment by NateWr** [comment]
Hi @Cphhygge,

The price and titles look aligned to me. Is this not what it looks like for you?
![selection_011](https://user-images.githubusercontent.com/2306629/27123731-ac614c1c-50e6-11e7-89fa-be97490288c7.png)

**Comment by Cphhygge** [comment]
It looks fine when it is on PC or tablet, but when the menu is used on Iphone or other smaller screens, the price jumps to the "next line". I can't seem to fix that, even though I put in the CSS:

@media (max-width: 768px) {

.fdm-columns-2 .fdm-column {
	width: 100%;
	float: none;
	margin: 0;
	}
}

**Comment by NateWr** [comment]
Hi @Cphhygge,

This is done intentionally, to ensure there is enough space for the item titles. If you keep the price on the top right, you may end up truncating the title space too much.

But if you still want to do it, you can use the following CSS code:

@media (max-width: 450px) {
  .fdm-menu .fdm-item-price-wrapper {
    text-align: right;
    position: absolute;
    width: 20%;
  }
}

**Comment by Cphhygge** [comment]
Hi again Nate!

This was exactly what I needed. Yea, I saw that it made some of the information (title line + price) overlap. But I adjusted the items it all the way down in the menu. 

You've been a great help. Where can I contribute to the plugin? :)  

All the best,

Christian.

**Comment by NateWr** [comment]
What kind of contribution were you thinking?

**Comment by Cphhygge** [comment]
Transfer money for your time and expertise, 'contribute' to your work? :)

**Comment by NateWr** [comment]
Ah right, Thanks for the offer but that's not necessary. I do appreciate reviews of the plugin here:

https://wordpress.org/support/plugin/food-and-drink-menu/reviews/
