### ISSUE TITLE
change the color of the name of menu item

### ISSUE THREAD

**Issue by Susi888** [NateWr/food-and-drink-menu#45]
Hi!
I am absolutely new to the subject and have a question:
How can I change the color and possibly also the font of the name of menu item? In the editor I have these options only for the description of menu item, but not for the name.
And my problem is that it has a black background and it looks unreadable
Thank you in advance for your answers.
Susi

**Comment by NateWr** [comment]
Hi @Susi888, this site is only for raising development issues for new features and bugs with the plugin. I've responded to your request on the WordPress support forums, so let's continue the discussion there.
