### ISSUE TITLE
[docs] Menu item?

### ISSUE THREAD

**Issue by strarsis** [NateWr/food-and-drink-menu#47]
Have I missed this feature or can a Food and Drink Menu plugin menu added as menu item?
I would have to use a hardcoded URL to it otherwise.

**Comment by NateWr** [comment]
Yes. Go to Appearance > Menus and in the list on the left, where you see Pages and Posts, you should see an option for Menus and Menu Items.

If you don't see this option, you may need to activate it in the Screen Options on that page. You can learn more about the Screen Options feature here: https://make.wordpress.org/support/user-manual/getting-to-know-wordpress/screen-options/

**Comment by strarsis** [comment]
Yes, it was there. Its german translation looks very similar to 'menu' in context of navigation menu, hence I ignored it first.
