### ISSUE TITLE
FDM templates

### ISSUE THREAD

**Issue by strarsis** [NateWr/food-and-drink-menu#49]
It is possible to select a page template in a FDM menu in backend, 
is it also possible to create a template (in theme) that is only selectable for a FDM menu?

**Comment by NateWr** [comment]
Hi @strarsis,

> It is possible to select a page template in a FDM menu in backend,

Yes, if custom templates exist they will be selectable for a menu.

> is it also possible to create a template (in theme) that is only selectable for a FDM menu?

It looks like you can: https://developer.wordpress.org/themes/template-files-section/page-template-files/#creating-page-templates-for-specific-post-types

**Comment by strarsis** [comment]
@NateWr: Thanks! I also use fdm menu sections for partioning menus, e.g. the menu 'Wines' gets sections like 'Special Wines' and 'Regional Wines' for example.
However, in some cases the first section got the same title as the whole menu, then I want to hide it.
It doesn't seem to be possible to assign a template to a menu section instead to a whole menu?
I want to hide the title of first menu section.
