### ISSUE TITLE
Gutenberg blocks loose selection

### ISSUE THREAD

**Issue by JeePeeNL** [NateWr/food-and-drink-menu#53]
I tested Version 1.6.0 with Gutenberg.
It's awesome that you can easily select the menu/section/item. However, after saving the page and reopening it, the blocks have lost their selection. See this screenvideo where I show what happens.
https://drive.google.com/open?id=18JiBRbXqrhjn1I4uKrSLTQQoxTruY6vV

JP

PS: release notes say there is now a shortcode for menu sections. What's that shortcode? It's not shown when you create/edit a section and it's not described in the documentation yet.

**Comment by NateWr** [comment]
Hi @JeePeeNL, thanks as always for the testing. Can you try to reproduce this in an install without Divi, on a default theme with no other plugins? I'm not able to reproduce it myself.

> PS: release notes say there is now a shortcode for menu sections. What's that shortcode?

`[fdm-menu-section id=*]`. Documentation coming later today. I woke up to some other critical errors with v1.6 this morning so working on those, then docs update, then release announcement!

**Comment by JeePeeNL** [comment]
Thanks. Mmm I don't have a non Divi install with just FDM.
I just switched themes and disabled all other plugins. Same issue (also with 1.6.1.)

No need to fix if I am the only one where this happens as I probably won't be using Gutenberg for now. I only saw it because I was curious how it looked.

**Comment by NateWr** [comment]
Fixed this. Version 1.6.2 going up to the WordPress.org plugin repository now.

**Comment by JeePeeNL** [comment]
Cool you found it. I can confirm it's fixed now.

Thanks
JP
