### ISSUE TITLE
Sub-sections

### ISSUE THREAD

**Issue by strarsis** [NateWr/food-and-drink-menu#54]
@NateWr: E.g. for a salad there can be a big and a small portion.
So on the first column there should be 'salad' which spans two rows and 
in the second column 'big' and 'small' in two rows and then in a third row the price for each.
Is this possible with Food and Drink menu?

Edit: Hierarchical menu section taxonomy would make this possible.

**Comment by NateWr** [comment]
Hi @strarsis,

No, there's no support for sub-sections in menus. It's a [long-standing request](https://github.com/NateWr/food-and-drink-menu/issues/1), but I have preferred to recommend that people use alternate strategies for building complex menu layouts.

If you are using the Gutenberg editor in WordPress 5.0+, you can use the column and menu item blocks to construct your own menu layout: http://doc.themeofthecrop.com/plugins/food-and-drink-menu/user/advanced/complex-layouts.

If you are using the classic editor, you can see an old tutorial with some tips here: https://themeofthecrop.com/2014/07/31/achieve-complex-menu-layouts-food-drink-menu/.

**Comment by strarsis** [comment]
@NateWr: The Food and Drink menu plugin is installed and enabled, 
but I am unable to find the Gutenberg blocks as shown in the tutorial (http://doc.themeofthecrop.com/plugins/food-and-drink-menu/user/advanced/complex-layouts).
