### ISSUE TITLE
Multiple prices for each menu item

### ISSUE THREAD

**Issue by NateWr** [NateWr/food-and-drink-menu#6]
Paul Dossor brought up the use-case of when a menu item has multiple prices, such as "entree" and "main dish", or small/large. Perhaps the price mechanism should be extended to support unlimited prices with a label for each. It will have to be done carefully not to add too much complexity.

**Comment by Baysah** [comment]
Hello NateWr, this is a great plugin.... Just wanted to know if you will be adding this feature soon?
thanks for your hard work

**Comment by NateWr** [comment]
Hi @Baysah, I think I've answered you over at at the WordPress.org forums but feel free to ask if you have any more questions.

https://wordpress.org/support/topic/multiple-prices-1/#post-8251004

**Comment by NateWr** [comment]
@Baysah This is now implemented in the GitHub repo. It will go out with the next update to the plugin. But that won't be happening immediately because I have a bunch of other improvements I plan to make in this update.

**Comment by Baysah** [comment]
Thanks for your response @NateWr. Sounds like you are busy with some amazing updates, I will be looking forward to it. Thanks for a great plugin
